"""Install / remove the status line, and a self-check.

Plugins cannot ship a statusLine setting, so setup writes one into ~/.claude/settings.json that points
at a small launcher in the agent-eta home. The launcher follows the plugin_root pointer that every
SessionStart refreshes, so plugin updates (which move the plugin directory) need no re-setup.
An existing status line is kept: its output is shown first and it is restored on remove.
"""
import json
import os
import shlex
import shutil
import sys
import time

from . import backfill, config, store, tuning
from . import estimator as E

PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def settings_file():
    return os.path.join(os.path.expanduser("~"), ".claude", "settings.json")


def launcher_file():
    return config.path("statusline.sh")


def _launcher_text(wrap):
    fallback = "exec sh -c %s" % shlex.quote(wrap) if wrap else "cat >/dev/null"
    return (
        "#!/bin/sh\n"
        "# Agent ETA status line launcher (generated by `eta.py setup`, removed by `eta.py setup --remove`).\n"
        "ROOT=$(cat %s 2>/dev/null)\n"
        "PY=python3\n"
        "command -v python3 >/dev/null 2>&1 || PY=python\n"
        "if [ -n \"$ROOT\" ] && [ -f \"$ROOT/scripts/eta.py\" ]; then\n"
        "  exec \"$PY\" \"$ROOT/scripts/eta.py\" statusline\n"
        "fi\n"
        "# Plugin gone: fall back to the previous status line (if any).\n"
        "%s\n" % (shlex.quote(config.path("plugin_root")), fallback))


def _read_settings(path):
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as f:
        text = f.read()
    if not text.strip():
        return {}
    data = json.loads(text)  # let a parse error surface: never overwrite a file we cannot read
    if not isinstance(data, dict):
        raise ValueError("%s is not a JSON object" % path)
    return data


def install(lang=None, refresh=5, do_backfill=True, skip_session=None, out=print):
    os.makedirs(config.home(), exist_ok=True)
    store.connect()
    config.write_atomic(config.path("plugin_root"), PLUGIN_ROOT + "\n")
    cfg = config.load()
    if lang in ("zh", "en", "auto"):
        cfg["lang"] = lang

    spath = settings_file()
    settings = _read_settings(spath)
    launcher = launcher_file()
    current = settings.get("statusLine")
    if isinstance(current, dict) and current.get("command") and current.get("command") != launcher:
        cfg["previous_statusline"] = current
        cfg["wrap_command"] = current.get("command")
        out("• kept your existing status line; its output is shown above the ETA: %s" % current.get("command"))
    if os.path.exists(spath) and not os.path.exists(spath + ".agent-eta-backup"):
        shutil.copy2(spath, spath + ".agent-eta-backup")
        out("• backup: %s.agent-eta-backup" % spath)
    new = {"type": "command", "command": launcher, "refreshInterval": int(refresh)}
    if isinstance(current, dict) and current.get("padding") is not None:
        new["padding"] = current["padding"]
    settings["statusLine"] = new
    os.makedirs(os.path.dirname(spath), exist_ok=True)
    config.write_atomic(spath, json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
    config.write_atomic(launcher, _launcher_text(cfg.get("wrap_command")), mode=0o755)
    config.save(cfg)
    out("• status line -> %s (refresh every %ss)" % (launcher, refresh))
    out("• data dir: %s" % config.home())
    out("• language: %s" % config.lang(cfg))
    if do_backfill:
        files, runs = backfill.run(skip_session=skip_session)
        out("• imported %d past runs from %d transcripts" % (runs, files))
    conn = store.connect()
    if tuning.finished_runs(conn) >= tuning.FIRST_TUNE_RUNS:
        out("• estimator tuned on your history: " + tuning.describe(tuning.tune(conn)))
    return 0


def remove(out=print):
    cfg = config.load()
    spath = settings_file()
    settings = _read_settings(spath)
    current = settings.get("statusLine")
    if isinstance(current, dict) and current.get("command") == launcher_file():
        if cfg.get("previous_statusline"):
            settings["statusLine"] = cfg["previous_statusline"]
            out("• restored previous status line: %s" % cfg["previous_statusline"].get("command"))
        else:
            settings.pop("statusLine", None)
            out("• removed statusLine from %s" % spath)
        config.write_atomic(spath, json.dumps(settings, indent=2, ensure_ascii=False) + "\n")
    else:
        out("• statusLine is not ours; left unchanged")
    if os.path.exists(launcher_file()):
        os.remove(launcher_file())
    cfg["previous_statusline"] = None
    cfg["wrap_command"] = None
    config.save(cfg)
    out("• history kept in %s (delete that directory to erase it)" % config.home())
    return 0


def doctor(out=print):
    ok = True

    def check(cond, good, bad):
        nonlocal ok
        out(("✓ " + good) if cond else ("✗ " + bad))
        ok = ok and cond

    check(sys.version_info >= (3, 8), "python %s" % sys.version.split()[0], "python >= 3.8 required")
    conn = store.connect(create=False)
    check(conn is not None, "database %s" % store.db_path(), "no database yet (hooks have not fired)")
    if conn is not None:
        n_live = conn.execute("SELECT COUNT(*) FROM runs WHERE source='live'").fetchone()[0]
        n_all = conn.execute("SELECT COUNT(*) FROM runs").fetchone()[0]
        last = conn.execute("SELECT MAX(last_event_at) FROM runs WHERE source='live'").fetchone()[0]
        check(n_live > 0, "hooks are recording (%d live runs, %d total; last event %s)" % (
            n_live, n_all, time.strftime("%Y-%m-%d %H:%M", time.localtime(last)) if last else "-"),
              "no live runs recorded yet: is the plugin enabled? (/plugin, then restart Claude Code)")
        rec = tuning.record(conn)
        if rec is not None and rec["value"] is not None:
            tuned = E.tuned_values(conn)
            out("✓ estimator tuned on %d runs (K0=%s, half-life %gd, recalibration %s, SAFE_K=%g, %s)" % (
                rec["n_runs"] or 0, "∞" if rec["value"] == float("inf") else "%g" % rec["value"],
                tuned.get("half_life", E.RECENCY_HALF_LIFE_D), "on" if tuned.get("recal") else "off",
                tuned.get("safe_k", E.SAFE_K_DEFAULT), time.strftime("%Y-%m-%d %H:%M", time.localtime(rec["at"]))))
        else:
            out("· estimator not tuned yet (happens by itself after %d finished runs)" % tuning.FIRST_TUNE_RUNS)
    try:
        root = open(config.path("plugin_root"), encoding="utf-8").read().strip()
    except OSError:
        root = ""
    check(bool(root) and os.path.exists(os.path.join(root, "scripts", "eta.py")),
          "plugin root %s" % root, "plugin_root pointer missing or stale (%r)" % root)
    try:
        sl = _read_settings(settings_file()).get("statusLine") or {}
    except ValueError as e:
        sl = {}
        out("✗ cannot parse %s: %s" % (settings_file(), e))
    check(sl.get("command") == launcher_file() and os.path.exists(launcher_file()),
          "status line installed (refreshInterval %s)" % sl.get("refreshInterval"),
          "status line not installed: run /agent-eta:setup")
    err = config.path("error.log")
    if os.path.exists(err) and os.path.getsize(err):
        with open(err, encoding="utf-8", errors="replace") as f:
            tail = f.read()[-1500:]
        out("! recent errors in %s:\n%s" % (err, tail))
    return 0 if ok else 1
